import {updateInputPreview} from './explorer-input.js?v=io2';
import * as THREE from './vendor/three.module.js';
import {LineSegments2} from './vendor/lines/LineSegments2.js';
import {LineSegmentsGeometry} from './vendor/lines/LineSegmentsGeometry.js';
import {LineMaterial} from './vendor/lines/LineMaterial.js';
import {OrbitControls} from './vendor/OrbitControls.js';
const el=document.querySelector('#motion-stage'),status=document.querySelector('#motion-status');
const scenes=await fetch('public-scenes.json?v=paymentsign').then(r=>r.json()).then(rows=>rows.filter(s=>!s.real));
let robotMeshes=[],robotPoses;
let stageVisible=false, linePositions,lineColors,lineSegments=[],dirty=true,frameTimes=[],previousRender=0;
new IntersectionObserver(entries=>{stageVisible=entries[0].isIntersecting;dirty=true},{threshold:0}).observe(el);
let renderer,scene,camera,controls,cloud,gripper,lines,meta,positions,gt,grips,mode='pred',playing=true,progress=0,last=0,request=0;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0xe9ece9);el.append(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(64,1,.01,100);camera.up.set(0,0,1);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.addEventListener('change',()=>{dirty=true});controls.minDistance=.1;controls.maxDistance=6;controls.maxPolarAngle=Math.PI*.88;
const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();calibratedProjection();if(lines)lines.material.resolution.set(el.clientWidth,el.clientHeight)};new ResizeObserver(resize).observe(el);
function calibratedProjection(){if(!meta?.intrinsics)return;const k=meta.intrinsics,w=el.clientWidth,h=el.clientHeight,s=Math.min(w/k.width,h/k.height),fx=k.fx*s,fy=k.fy*s,cx=k.cx*s+(w-k.width*s)/2,cy=k.cy*s+(h-k.height*s)/2,n=camera.near,f=camera.far;camera.projectionMatrix.set(2*fx/w,0,1-2*cx/w,0,0,2*fy/h,2*cy/h-1,0,0,0,-(f+n)/(f-n),-2*f*n/(f-n),0,0,-1,0);camera.projectionMatrixInverse.copy(camera.projectionMatrix).invert();}
function pointObject(array,colors,size){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(array),3));if(colors){const linear=new Float32Array(colors.length);for(let i=0;i<colors.length;i++){const v=colors[i]/255;linear[i]=v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4)}geo.setAttribute('color',new THREE.BufferAttribute(linear,3));}const mat=new THREE.PointsMaterial({size,vertexColors:!!colors,color:colors?0xffffff:0xdf37ef,sizeAttenuation:false});mat.onBeforeCompile=s=>{s.fragmentShader=s.fragmentShader.replace('#include <clipping_planes_fragment>','#include <clipping_planes_fragment>\nif(length(gl_PointCoord-vec2(0.5))>0.5) discard;')};const o=new THREE.Points(geo,mat);scene.add(o);return o}
function clear(){linePositions=null;lineColors=null;lineSegments=[];robotMeshes=[];robotPoses=null;while(scene.children.length){const o=scene.children[0];o.geometry?.dispose();o.material?.dispose();scene.remove(o)}}
async function binary(url,gzip=false){const r=await fetch(url);if(!r.ok)throw Error('HTTP '+r.status);return gzip?new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer():r.arrayBuffer()}
async function loadPacked(base,m){let pack=null;if(typeof DecompressionStream!=='undefined'){const r=await fetch(base+'web-pack.json');if(r.ok)pack=await r.json()}m.webPack=pack;if(!pack)return Promise.all(['pred','gt','gripper','colors'].map(n=>n==='gt'&&!m.hasGT?null:binary(base+n+'.bin')));status.textContent='Loading compressed dense trajectories…';const [x,d,g,c]=await Promise.all(['xyz0','delta','gripper','colors'].map(n=>binary(base+n+'.bin.gz',true)));const first=new Float32Array(x),delta=new Int16Array(d),pred=new Float32Array(m.frames*m.points*3);pred.set(first);for(let i=0;i<delta.length;i++)pred[first.length+i]=first[i%first.length]+delta[i]*pack.quantum_m;return [pred.buffer,null,g,c]}

async function load(i){frameTimes=[];previousRender=0;const token=++request;status.textContent='Loading 3D trajectories…';playing=false;const m=scenes[i],base=m.base;document.querySelector('#input-language').textContent='Loading observation…';document.querySelectorAll('[data-motion]').forEach(b=>b.setAttribute('aria-pressed',i===Number(b.dataset.motion)));try{const buffers=m.coveragePacked?await loadPacked(base,m):await Promise.all(['pred','gt','gripper','colors'].map(n=>(n==='gt'&&!m.hasGT?Promise.resolve(null):fetch(base+n+'.bin').then(r=>{if(!r.ok)throw Error('Trajectory request failed');return r.arrayBuffer()}))));if(token!==request)return;meta=m;positions=new Float32Array(buffers[0]);gt=buffers[1]?new Float32Array(buffers[1]):null;mode="pred";document.querySelector("#motion-mode").value="pred";document.querySelector("#motion-mode").options[1].disabled=!m.hasGT;grips=new Float32Array(buffers[2]);clear();cloud=pointObject(positions.slice(0,m.points*3),new Uint8Array(buffers[3]),m.pointSize||5.0);gripper=pointObject(grips.slice(0,m.gripperPoints*3),null,6);lines=new LineSegments2(new LineSegmentsGeometry(),new LineMaterial({vertexColors:true,transparent:true,opacity:.85,linewidth:2.2,resolution:new THREE.Vector2(el.clientWidth,el.clientHeight)}));scene.add(lines);camera.fov=m.fov||64;camera.updateProjectionMatrix();calibratedProjection();camera.position.fromArray(m.camera);camera.up.set(0,0,1);controls.target.fromArray(m.target);controls.update();await loadRobot(base,token,m.geometryBase);if(token!==request)return;progress=0;playing=!matchMedia('(prefers-reduced-motion:reduce)').matches;document.querySelector('#motion-play').textContent=playing?'Pause':'Play';document.querySelector('#motion-title').textContent=m.title;document.querySelector('#motion-select').value=i;const inputRoot='assets/explorer-inputs-20260923/'+encodeURIComponent(m.key)+'/';const input=await fetch(inputRoot+'input.json?v=rgbfix20260925').then(r=>{if(!r.ok)throw Error('Input unavailable');return r.json()});if(token!==request)return;input.rgbURL=inputRoot+input.rgb+'?v=rgbfix20260925';document.querySelector('#motion-rgb').src=input.rgbURL;document.querySelector('#input-rgb-original').href=input.rgbURL;document.querySelector('#input-language').textContent='“'+input.instruction+'”';updateInputPreview(input,positions.slice(0,m.points*3),new Uint8Array(buffers[3]));status.textContent=`${m.domain} · ${m.points.toLocaleString()} scene points · ${m.gripperPoints} predicted gripper points · Checkpoint ${m.checkpoint} · Full-arm IK`;document.querySelectorAll('[data-motion]').forEach(b=>b.setAttribute('aria-pressed',i===Number(b.dataset.motion)));paint()}catch(e){status.textContent='Unable to load this scene. Select another sample or retry.';console.error(e)}}
async function loadRobot(base,token,geometryBase){
 const root=geometryBase||base,prefix='';
 const [parts,buf,pbuf]=await Promise.all([fetch(root+prefix+'geometry.json').then(x=>x.json()),fetch(root+prefix+'geometry.bin').then(x=>x.arrayBuffer()),fetch(base+prefix+'robot-poses.bin').then(x=>x.arrayBuffer())]);if(token!==request)return;
 el.dataset.robotParts=String(parts.length);el.dataset.robotVariant=prefix?'task-arms-only':'original';el.dataset.robotBytes=String(buf.byteLength+pbuf.byteLength);robotPoses=new Float32Array(pbuf);scene.add(new THREE.HemisphereLight(0xffffff,0x8b9399,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(1,-1,3);scene.add(light);
 for(const part of parts){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(buf,part.offset,part.vertices).slice(),3));geo.setIndex(new THREE.BufferAttribute(new Uint32Array(buf,part.offset+part.vertices*4,part.indices).slice(),1));geo.computeVertexNormals();const color=new THREE.Color().setRGB(...part.color,THREE.SRGBColorSpace);const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color,transparent:true,opacity:.38,roughness:.65,metalness:.05,side:THREE.DoubleSide,depthWrite:false}));scene.add(mesh);robotMeshes.push(mesh)}
}
const robotM1=new THREE.Matrix4(),robotM2=new THREE.Matrix4(),rp1=new THREE.Vector3(),rp2=new THREE.Vector3(),rq1=new THREE.Quaternion(),rq2=new THREE.Quaternion(),rs1=new THREE.Vector3(),rs2=new THREE.Vector3();
function paint(){if(!meta)return;const T=meta.frames,N=meta.points,t=Math.min(1,progress)*(T-1),a=Math.floor(t),b=Math.min(a+1,T-1),f=t-a,source=mode==='pred'?positions:gt;for(const [obj,data,n] of [[cloud,source,N],[gripper,grips,meta.gripperPoints]]){const dest=obj.geometry.attributes.position.array;for(let j=0;j<n*3;j++)dest[j]=data[a*n*3+j]*(1-f)+data[b*n*3+j]*f;obj.geometry.attributes.position.needsUpdate=true;obj.frustumCulled=false}
if(robotPoses)robotMeshes.forEach((mesh,j)=>{const n=robotMeshes.length;robotM1.fromArray(robotPoses,(a*n+j)*16).transpose();robotM2.fromArray(robotPoses,(b*n+j)*16).transpose();robotM1.decompose(rp1,rq1,rs1);robotM2.decompose(rp2,rq2,rs2);mesh.position.copy(rp1).lerp(rp2,f);mesh.quaternion.copy(rq1).slerp(rq2,f);mesh.scale.copy(rs1).lerp(rs2,f)});
const show=document.querySelector('#motion-trails').checked;lines.visible=show;
if(show){
 if(!linePositions){
  const stops=['#f4a338','#f6d16c','#84ced5','#568bcc','#6542ad'].map(c=>new THREE.Color(c)),magenta=new THREE.Color('#df37ef');
  lineSegments=[];
  for(let k=1;k<T;k++)for(const [ids,n,isGrip] of [[meta.tracks,N,false],[Array.from({length:meta.gripperPoints},(_,j)=>j),meta.gripperPoints,true]])for(const j of ids)lineSegments.push({k,j,n,isGrip});
  linePositions=new Float32Array(lineSegments.length*6);lineColors=new Float32Array(linePositions.length);
  lineSegments.forEach(({k,isGrip},i)=>{const x=k/(T-1)*4,l=Math.min(3,Math.floor(x)),c=isGrip?magenta:stops[l].clone().lerp(stops[l+1],x-l);lineColors.set([c.r,c.g,c.b,c.r,c.g,c.b],i*6)});
  lines.geometry.setPositions(linePositions);lines.geometry.setColors(lineColors);
 }
 let count=0;const buf=lines.geometry.attributes.instanceStart.data.array;
 for(let i=0;i<lineSegments.length;i++){
  const {k,j,n,isGrip}=lineSegments[i];if(k-1>t)break;const data=isGrip?grips:source,frac=Math.min(1,t-(k-1)),off=((k-1)*n+j)*3,next=(k*n+j)*3;
  for(let q=0;q<3;q++){buf[i*6+q]=data[off+q];buf[i*6+3+q]=data[off+q]*(1-frac)+data[next+q]*frac}count++;
 }
 lines.geometry.instanceCount=count;lines.geometry.attributes.instanceStart.data.needsUpdate=true;lines.frustumCulled=false;
}
dirty=true;document.querySelector('#motion-time').value=Math.round(progress*1000);document.querySelector('#motion-frame').textContent=`${Math.round(t)} / ${T-1}`}
scenes.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=s.domain+' · '+s.title;document.querySelector('#motion-select').append(o);{const b=document.createElement('button');b.dataset.motion=i;b.setAttribute('aria-label',s.title);b.setAttribute('aria-pressed','false');b.title=s.domain+' · '+s.title;const im=document.createElement('img');im.src=s.base+'poster.jpg';im.alt='';im.loading='lazy';const label=document.createElement('span');label.textContent=s.title;b.append(im,label);b.onclick=()=>load(i);document.querySelector('#motion-samples').append(b)}});
document.querySelector('#motion-select').onchange=e=>load(Number(e.target.value));window.addEventListener('select-conditional-scene',e=>{const i=scenes.findIndex(s=>s.key===e.detail);if(i>=0)load(i)});
document.querySelector('#motion-play').onclick=e=>{playing=!playing;e.target.textContent=playing?'Pause':'Play'};document.querySelector('#motion-time').oninput=e=>{progress=e.target.value/1000;playing=false;document.querySelector('#motion-play').textContent='Play';paint()};document.querySelector('#motion-reset').onclick=()=>{if(meta){camera.position.fromArray(meta.camera);camera.up.set(0,0,1);controls.target.fromArray(meta.target);controls.update()}};document.querySelector('#motion-trails').onchange=paint;document.querySelector('#motion-mode').onchange=e=>{mode=e.target.value;paint()};
function animate(ms){requestAnimationFrame(animate);const dt=Math.min((ms-last)/1000,.05);last=ms;if(playing&&meta&&!document.hidden&&stageVisible){progress+=dt/5;if(progress>1.25)progress=0;const saved=progress;progress=Math.min(1,progress);paint();progress=saved}if(stageVisible&&!document.hidden){controls.update();if(dirty){renderer.render(scene,camera);el.dataset.worldUp='0,0,1';el.dataset.horizonRollDeg=(Math.atan2(camera.matrixWorld.elements[2],camera.matrixWorld.elements[6])*180/Math.PI).toFixed(4);if(previousRender&&playing){frameTimes.push(ms-previousRender);if(frameTimes.length>180)frameTimes.shift();if(frameTimes.length%30===0){const sorted=[...frameTimes].sort((a,b)=>a-b);el.dataset.frameP95Ms=sorted[Math.floor(sorted.length*.95)].toFixed(1);el.dataset.frameMeanMs=(frameTimes.reduce((a,b)=>a+b,0)/frameTimes.length).toFixed(1)}}previousRender=ms;dirty=false}}else previousRender=0;}const lazyStart=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){lazyStart.disconnect();if(request===0)load(0)}},{rootMargin:'200px'});lazyStart.observe(el);requestAnimationFrame(animate);
}catch(e){status.textContent='This browser could not start WebGL. The scene videos remain available below.';console.error(e)}
